# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_names', models.CharField(max_length=60)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
