# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_lowercase_name_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permission_user', to='authentication.Permission'),
        ),
    ]
