# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('PENDING', 'Pendiente'), ('IN_PROCESS', 'En Proceso'), ('CLOSED', 'Resuelto y cerrado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket',
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
